### ISSUE TITLE
request the Code

### ISSUE THREAD

**Issue by Shashika007** [cumtxz/STCM-SLAM#1]
Hey! 

I read your paper. When will you be able to upload your code? 

Thanks 

Shashika

**Comment by edgar-explorer** [comment]
Thank you very much for your interest in our project. I have graduated from china university of mining and technology. Recently, I have been busy with my work. If you did not understand and part of our STCM-SLAM, please do not hesitate to send email to me (cumtchenchang@163.com). In fact, our paper has been explained detailly. You can improve our method according to your application scenes. If our paper is helpful to your work, please cite our paper. Thank you.
